### ISSUE TITLE
Lifetime of Inbox queue

### ISSUE THREAD

**Issue by StefanBertels** [louthy/echo-process#22]
I have a local actor with slow inbox function.
My main / outer method (which spawns the actor) tells it a larger number of message objects.

Currently when shutting down this actor or the whole process system unprocessed messages get lost / do not get processed.

Is there a way to wait for this or all actors to process any waiting messages? I mean I'm in a similar state when calling OnCompleted on some Subject (Rx) and my actor is something like the subscription functions, so there should be some option to shutdown after processing the remaining messages (shutdownAfterInboxEmpty). I guess this might be more tricky to implement for shutdownAll  -- for me shutting down some specific actors would work fine.

**Comment by StefanBertels** [comment]
I tried this workaround:

```
// long loop with `tell`, filling up mailBox

var dummy = process.Ask<Unit>(dummyMessage);   // block until mailbox is empty
process.ShutDown();
```

But I get `System.TimeoutException` "Request timed out" when calling `Ask()`.

**Comment by StefanBertels** [comment]
Is there something in echo making delivery reliable in a "at least one" sense?

AFAIK actor model (as in echo) work as "fire and forget" -- at least you don't know when the message will arrive.

I'm thinking about giving messages e.g. serial numbers. If something goes wrong this could be handled the same way as when the system startsup: every receiving actor knows the highest serial number he successfully received and handled. When an actor starts, it could send some "replay" message to actors he listens to ("please tell me all messages with number > xy").

I'm a little bit afraid about overhead because every actor needs to use some journaling / event store, but I guess this is inevitable. At least this might be a general solution with event sourcing like separation of commands and events. 

I'm more afraid about the fact receiving actors have to know (all) sending actors for this to be reliable. Feels like Observable pattern fits better since receiver subscribes to sender. Maybe sender is some cold observable (replay journal) but I don't want to replay everything.

I know this is something message bus systems or message brokers try to solve.
But I feel there could/should be some small local solution without central infrastructure.

Any thoughts?

**Comment by StefanBertels** [comment]
Hmm. My approach using some serial number (see previous comment) has some design flaw:
Actor model in general does not ensure that message are received in order of submission.
So receiver cannot be sure to have read all messages until some serial number.

Probably I need some event store in sending actor and a replay function that replays every message in event store again after X where X is just a point in time. The point will be DateTime.MinValue if I need every event from the beginning or can move forward to reduce scalability problems (like X = now minus 1 month) for startup case.

I'm still unsure whether replay is the best way to solve this. At least this might be a problem with limited inbox capacity (#23).

Some other way would be to send some ACK after receiving actor finishes processing so sending actor could drop the event (transaction). But I think this does not fit to actor model at all (what if there are two or an unknown count of receiving actors / observable style).

**Comment by louthy** [comment]
> Is there a way to wait for this or all actors to process any waiting messages? 

Unfortunately not, no.  The only way is to persist them so they can be processed on startup.  In principle I don't have a problem with the idea of adding a Process setting that stops the System shutdown, although I haven't investigated the complexities of that system.

Obviously a persistent inbox would be better if you're looking for a guaranteed inbox.

> AFAIK actor model (as in echo) work as "fire and forget" -- at least you don't know when the message will arrive.

That is a tenet of the actor model.  But with `echo` there are [5 retries which back-off](https://github.com/louthy/echo-process/blob/master/Echo.Process.Redis/RedisClusterImpl.cs#L433) that are entirely synchronous.  So if your `tell` completes then it's in Redis (and will therefore be processed eventually).

> Any thoughts?

Not really.  I'm only seeing you suggest solutions.  I don't know the problem you're trying to solve.

**Comment by StefanBertels** [comment]
Ok. Problem is I don't have a Redis cluster here ;-)
(And I favor some event sourcing pattern to be able to replay events of the past after changing business logic.)

Just waiting on shutdown doesn't solve my issue because I have to handle crashes, too.
Therefore I will close this issue.
