### ISSUE TITLE
Feature request: Inbox pre/post hook functions

### ISSUE THREAD

**Issue by OlduwanSteve** [louthy/echo-process#24]
It would be very useful for profiling/diagnostics if I could set a pair of callbacks that are invoked before/after every setup and inbox call. Something like:

```
Echo.Process.PreInboxHook = (ProcessId pid, Option<object> msg) => Stopwatch.StartNew();

Echo.Process.PostInboxHook = (object state, ProcessId pid, Option<object> msg) => { ((StopWatch)state).Stop(); // now do some logging }
```

**Comment by StefanBertels** [comment]
I built this myself by having wrapper functions ([AOP](https://en.wikipedia.org/wiki/Aspect-oriented_programming) / decorating functions) like this:

I have a container holding a function pair (setup + inbox):
```
public class ActorDefinition<S, T>
{
    public Func<S, T, S> InboxFn {get; set;}
    public Func<S> SetupFn {get; set;}
}
```

You can now have some enriched state like
```
public class StateWithStopWatch<S>: IDisposable
{
    public StopWatch StopWatch;
    public S InnerState;

    StateWithStopWatch(S inner)
    {
        StopWatch = StopWatch.StartNew();
        InnerState = inner;
    } 

    public ReplaceState(S newInner)
    {
        InnerState = inner;
    }

    public Dispose()
    {
        // maybe log stopwatch here
        InnerState?.Dispose();
    }
}
```

Now you need some enrichment function:
```
public static ActorDefinition<StateWithStopWatch<S>, T> AddStopWatch<S, T>(Func<S> setupFn, Func<S, T, S> inboxFn)
{
   return new ActorDefinition()
   { SetupFn = () => StateWithStopWatch<S>(setupFn()),
     InboxFn = (stateWithStopWatch, msg) => stateWithStopWatch.Replace(inboxFn(stateWithStopWatch.InnerState, msg))
   }
}
```

Final part: spawn a new actor using the new actordefinition.

Note: all this is just pseudo code / might have typos.

You can add aspects beyond logging in a similar way, e.g. add your own persistence like event streaming (having an event store in your state).

**Comment by louthy** [comment]
I have now added support for a `Shutdown` function.  It runs before the state item is disposed before a restart or a kill.
