### ISSUE TITLE
Question: LifeTime / order of spawning

### ISSUE THREAD

**Issue by StefanBertels** [louthy/echo-process#25]
Hi,

is there some documentation / information regarding lifetime / activity of actors? 

Can I wire up actors in a way that makes sure I don't lose a message even if the receiving actor is spawned after producing actor?

Example:

1. spawn some "producing" actor 
2. spawn some "trigger" actor (think of timer / FileSystemwatcher)
3. spawn some "receiving" actor

After spawning trigger actor this trigger actor might immediately start by telling the producer which itself starts publishing valuable messages. If this happends before 3 I might lose the latter.

Flow: trigger ==(tell)==> producer ==(publish)==> receiver(s)

I don't want to spawn trigger actor after receiving actor (swap 2 and 3) because producer and trigger will be spawned by the same function. Trigger should be just some child / helper actor for producer actor.

I could spawn "receiving" actor first (3 before 1+2). But I could not manage to wire producer and receiver this way. subscribe and observe require a valid ProcessId.

I want to avoid some (quick&dirty) timing solution like starting trigger message with a delay.

**Comment by StefanBertels** [comment]
Ah, just found something in spawn: parameter `bool lazy`. So at least there is some way...

Still asking: is there some other solution than spawning/starting trigger last?

Side question: Is it ok / recommended to create child actors during setupFn of a parent actor (seems `Self` is only available during inboxFn)?

**Comment by louthy** [comment]
I don't quite follow your spawning question.  But you can't send a message to a process that has never existed.  But if it is a persistent process and has existed before (and not killed) then you can send a message to its inbox which will be collected when it spawns again.

One thing I'd sat is try not to fight the hierarchy, use the supervision hierarchy to guarantee creation order and deal with routing.

Yes, it is recommended to spawn children in the setup function, it's the best approach for creating your hierarchy.  `Self` should be valid in the setup.  Do you have a repro for that to not be the case?

**Comment by StefanBertels** [comment]
My modification #26 works fine for me (with my local fork) and solves my original problem.
Do you think you could merge that PR (and close #26 and this one)?
