### ISSUE TITLE
Interfaces should not implement IDisposable

### ISSUE THREAD

**Issue by bender2k14** [louthy/echo-process#27]
On [this line of code](https://github.com/louthy/echo-process/blob/d826d9034a4a9dddfbaf07f20090ee06dcba46c6/Echo.Process/ActorSys/IActor.cs#L11), `IActor` implements `IDisposable`.  Mark Seemann, an expert in dependency injection and author of [Dependency Injection in .NET](https://www.amazon.com/Dependency-Injection-NET-Mark-Seemann/dp/1935182501), [says](http://blog.ploeh.dk/2014/08/25/decommissioning-decoraptors/) that an interface should not implement `IDisposable`.  Here is the relevant text.

> Concrete types can implement IDisposable, but interfaces should not, since IDisposable is an implementation detail. (I do realize that some interfaces defined by the .NET Base Class Library derives from IDisposable, but I consider those Leaky Abstractions. As Nicholas Blumhardt [put it](https://cca.codeplex.com/discussions/82987): "an interface [...] generally shouldn't be disposable. There's no way for the one defining an interface to foresee all possible implementations of it - you can always come up with a disposable implementation of practically any interface.")

And indeed you have the class [`NullProcess`](https://github.com/louthy/echo-process/blob/d826d9034a4a9dddfbaf07f20090ee06dcba46c6/Echo.Process/ActorSys/NullProcess.cs) that implements `IActor` but doesn't need to do any disposing.

**Comment by bender2k14** [comment]
I'm fact, I think it suffices to consider the [documentation of `IDisposable`](https://msdn.microsoft.com/en-us/library/system.idisposable(v=vs.110).aspx) itself.

> Implement `IDisposable` only if you are using unmanaged resources directly.

Since an interface doesn't use any resources directly, it should not implement `IDisposable`.

**Comment by StefanBertels** [comment]
I don't think this issue is a real problem due to `IActor` being internal.
But it's interesting regarding general design.

@bender2k14 Do you think this is broken with Stream, in a similar way? FileStream needs to be disposed (because of locks and/or flushing) but e.g. MemoryStream not.

Some disadvantage might be that you cannot write code 

```
using(var x = CreateSomeActor())
{
   x.DoSomeThing();
}
```
anymore.

Found this related one: https://stackoverflow.com/questions/10513948/declare-idisposable-for-the-class-or-interface

**Comment by bender2k14** [comment]
> Do you think this is broken with Stream, in a similar way? FileStream needs to be disposed (because of locks and/or flushing) but e.g. MemoryStream not.

"Broken" is a strong word.  I would say "not ideal".

> Some disadvantage might be that you cannot write code...
> 
```
using(var x = CreateSomeActor())
{
   x.DoSomeThing();
}
```

Depends on the return type of `CreateSomeActor`.  A good principle to follow is be liberal in what you take in and conservative in what you give out.  For a method's return type, that means return a stronger, more specific / derived type instead of a weaker, less specific / derived type.  In particular, this method could return `MyDisposableActorClass` instead of `IActor`.  However, there are good reasons to deviate from this principle.

> Found this related one: https://stackoverflow.com/questions/10513948/declare-idisposable-for-the-class-or-interface

Indeed.  The OP has accepted one answer while a different answer has the most up votes.  I think the accepted answer is consistent with your position while I agree with the answer that has the most up votes.  There are also other answers for both positions that are neither the accepted answer nor have the most votes.

From the accepted answer, I think the relative quote is

> the rule of thumb when designing interfaces is to favor "ease-of-use" over "ease-of-implementation"

I don't know how to justify that this is _the_ rule of thumb (or what I would call a principle) when designing interfaces.  I agree that it is _a_ rule of thumb or principle.  Another principle when designing interfaces is the [interface segregation principle](https://en.wikipedia.org/wiki/Interface_segregation_principle), which states that no client should be forced to depend on methods it does not use.

Since the user of a type instance should not be responsible for its lifetime management, the user shouldn't use the `Dispose` method, so the user shouldn't be forced to depend on the existence of the `Dispose` method, so the scope of the `Dispose` method should be as specific as possible to allow the user to depend on a weaker type that does not contain the `Dispose` method.

**Comment by louthy** [comment]
There's nothing I love more than quotes on OO coding.  

The interfaces are not exposed and it simplifies and optimises the shutdown procedure (which could be working on 10s of 1000s of processes).
