### ISSUE TITLE
Internal Exception Response on ask

### ISSUE THREAD

**Issue by SirHoneyBiscuit** [louthy/echo-process#31]
Paul,

I really enjoy both ```Language-Ext``` and ```Echo-Process```. It's changed the way I code and how I think about solving problems. I do have a possible issue with some exception handling.  

When asking an inbox that doesn't exist in the process system, internally the ProcessException is thrown saying as much but that exception is never returned to the ask. The ask only fails after a timeout has occurred.  

In the below case ```RaisesExceptionsOnAskWithInboxException```, when receiving an exception from an inbox, the exception is sent back right away and is available via the inner exception on the ProcessException.

In the case ```DoesntRaiseExceptionOnAskWithNoInbox``` , the only exception returned is a system timeout exception. I would expect to fail fast in this scenario. As soon as it's know there is no registered inbox of that name, and exception should be returned. 

While the end result is the same (being that an exception is raised), we do have to wait that additional time for the exception to bubble up. In our application, we are forced to set the timeout a bit higher due to legacy API calls and their high failure frequency. We would also like to treat a timeout exception differently than an internal exception when tackling our management strategies. 

I am using Xunit as my test runner. 

```
    public class AskFixture : IDisposable
    {
        public AskFixture()
        {
            initialiseFileSystem();
            var command = Router.leastBusy
                (
                    Name: "cmd",
                    Count: 5,
                    Inbox: (string msg) =>
                    {
                        throw new Exception("Hello");
                    }

                );
            register(command.Name, command);
            subscribe<Exception>(Errors(), e => raise<Unit>(e));
        }
        public void Dispose() => shutdownAll();
    }


    public class AskError : IClassFixture<AskFixture>, IDisposable
    {
        public readonly ITestOutputHelper Output;
        public readonly IReadOnlyCollection<IDisposable> Trash;

        public AskError()
        {
            Trash = List(
                subscribe<Exception>(Errors(), e => 
                  Output.WriteLine($"{e.GetType().ToString()} {e.Message}"))
            );
        }

        public void Dispose()
        {
            Trash.Iter(t => t.Dispose());
        }

        [Fact]
        public void DoesntRaiseExceptionOnAskWithNoInbox()
        {
            Assert.Throws<Echo.ProcessException>(() => ask<string>("@test", "You there?"));
        }

        [Fact]
        public void RaisesExceptionsOnAskWithInboxException()
        {
            Assert.Throws<Echo.ProcessException>(() => ask<string>("@cmd", "You there?"));
        }
    }
```

**Comment by louthy** [comment]
Never mind, I've found it - it's fixed in `v2.0.44`.  The `ask` will throw a `ProcessException` now if there's no processes in the role-group.  Note if you do a remote `ask` with a regular `ProcessId` rather than the registered name (`@role:name`) then you will still have to wait for timeouts.
