### ISSUE TITLE
RedisClusterImpl.QueryProcessMetaData duplicate key error

### ISSUE THREAD

**Issue by OlduwanSteve** [louthy/echo-process#33]
I was seeing the following exception repeatedly when attempting to query process metadata in redis (stack trace at bottom):

An element with the same key already exists in the Map 

I can't immediately see how this is possible, but it looks like under some circumstances:

- QueryKeys can return duplicates

or

- QueryKeys can return keys that are different, but equivalent in the ProcessId comparison

Additional info:

This started happening after the server was rebooted. 
A recycle of the app pool fixed it.

```
LanguageExt.MapModule.Add[OrdK,K,V](MapItem`2 node, K key, V value) at 
LanguageExt.MapModule.Add[OrdK,K,V](MapItem`2 node, K key, V value) at 
LanguageExt.MapModule.Add[OrdK,K,V](MapItem`2 node, K key, V value) at 
LanguageExt.MapInternal`3.AddRange(IEnumerable`1 range) at 
Echo.RedisClusterImpl.QueryProcessMetaData(String keyQuery) at 
LanguageExt.ClassInstances.FOption`2.<>c__DisplayClass2_0.<Map>b__0(A a) at 
LanguageExt.ClassInstances.MOption`1.Bind[MonadB,MB,B](Option`1 ma, Func`2 f) at 
LanguageExt.ClassInstances.FOption`2.Map(Option`1 ma, Func`2 f) at 
LanguageExt.Option`1.Map[B](Func`2 f) at
Echo.Process.queryProcessMetaData(String keyQuery, SystemName system) 
```

**Comment by louthy** [comment]
I believe this will be fixed with changes made in lang-ext `AddRange`.
