### ISSUE TITLE
System.Exception: 'observe' should not be be used from within a process' message loop.

### ISSUE THREAD

**Issue by StefanBertels** [louthy/echo-process#40]
When creating some actor hierarchy I get this error message:

`System.Exception: 'observe' should not be be used from within a process' message loop.`

Reason: I call `observe` when initalising state (SetupFn). 

Why is `observe` a problem there (it's not in inboxFn)?
Can we allow this (change this)?

The reason I want to do this is that I start some actors and wire them together using tell/ask/publish/observe. All these actors are childs of some "container" actor.

I just wanted to make those actors child of the container because I setup an error `Strategy` that should apply to all children. Spawning (and wiring) the actors during Setup does this. As an extra I can restart the whole subset by just restarting the container actor.

**Comment by StefanBertels** [comment]
Just a note: I know there is subscribe which is designed to be called by the receiving actor.
But I find it cleaner to do the wiring on container level so the child actors' code does not depend on each other.

It's clear that the subscription to observe will result in an IDisposable that should be handled. I pass this Disposable to the container actor's state, so shutting down the container will unsubscribe automatically (the child actors are probably already gone then).

**Comment by StefanBertels** [comment]
I read your comment:
```
/// Because this call is asychronous it could allow access to the message loop, therefore
/// you can't call it from within a process message loop.
```
Obviously `onNext` will be called async and outside of message handler context (so e.g. `Self` cannot be used). 
Is this the only reason for not allowing this?

Even with this context issue I think Observables / observe would be quite useful here -- making all those great observable operators available to actors / actor message flow. Maybe add some `observeUnsafe` function?

But maybe I'm missing another issue here... (?)

**Comment by louthy** [comment]
You have access to the state as part of the closure, so it pretty much breaks the encapsulation idea, and so anything that works like that I don't really want to _officially_ encourage.

**Comment by StefanBertels** [comment]
My main use case for this is:

I have wrapper-actors that have code in setupFn that just starts sub-actors (with some wiring) for some module. Different modules have differen wrapper actors.

Those wrapper actors allow me to 
1. organise my actors in a hierarchical way (/root/user/wrapper-for-module-1/some-actor)
2. set a Strategy for all these sub-actors at once
3. easily restart a module using both strategy error handling and explicit via restart(pidWrapperModule1)

It would be great if I could wire the sub-actors here in the same way I can wire them up in Program.Main => using publish/observe.

**Comment by louthy** [comment]
@StefanBertels  How about an `observeUnsafe` - so it's explicit that you're stepping into a potential non-deterministic situation?  I'd feel better about that as a name as anything labelled unsafe always makes devs think twice.

**Comment by StefanBertels** [comment]
Thanks! Maybe add a hint to observeUnsafe (and a warning) to the error message of observe.

**Comment by StefanBertels** [comment]
Can you push sources? I'm currently using the source code version and that seems to be behind.
