### ISSUE TITLE
State diposed during inboxFn

### ISSUE THREAD

**Issue by StefanBertels** [louthy/echo-process#42]
(I added this as comment in #39, but I think it wasn't fixed (at least not by my PR) so here as separate issue.)

I think there is a problem with lifetime of state if state object is IDisposable.

If the actor gets stopped, the state will be disposed -- regardless whether inboxFn is still running.
At least this will result in an error when accessing the state after Dispose has been called on it.

To solve this issue I think about two workarounds:

a) lock some internal object in dispose and during processing of inboxFn so shutting down an actor will wait for the inboxFn to finish (force clean shutdown, even if this will block for some time).

b) if inboxFn throws errors check whether state was disposed (track this) and handle situation in a special way (e.g. always `ForwardToSelf` with ProcessDirective.None). Might catch errors that aren't caused by Disposing.

Both solutions have pro and cons. @louthy: I'm interested in your point of view / how the library should in general handle this. The current implementation just sees an error and will cause normal Strategy handling. This is suboptimal because if an error occurs I might restart Parent actor which will restart siblings of Self (other children of Parent) and they might run into state-disposed-issue which will itself result in error handling / Strategy processing.

I'm not sure but currently I think the library should go way a).

Test code:
```
 [Collection("Actor")] // https://xunit.github.io/docs/running-tests-in-parallel
    public static class SafeDisposableStateTests
    {
        [Fact]
        static void Test()
        {
            ProcessConfig.initialise();
            var pid = spawn("test", () =>
                {
                    Console.WriteLine($"{DateTime.Now} created state!");
                    return Disposable.Create(() => Console.WriteLine($"{DateTime.Now} diposed state!"));
                },
                (IDisposable _, string msg) =>
                {
                    Console.WriteLine($"{DateTime.Now} {msg} inboxFn 1");
                    Thread.Sleep(2000);
                    Console.WriteLine($"{DateTime.Now} {msg} inboxFn 2");
                    return _;
                });

            tell(pid, "bla", 1 * second);
            restart(pid);

            Thread.Sleep(2000);
            restart(pid);
            Thread.Sleep(2000);
            Process.shutdownAll();
        }
    }
```

**Comment by louthy** [comment]
Try `2.0.51` - I haven't done any testing, so if you could give it a try, it should sort it.

**Comment by StefanBertels** [comment]
Looks good. Thank you very much!
