### ISSUE TITLE
Get some notification during inboxFn when actor gets killed (CancellationToken)

### ISSUE THREAD

**Issue by StefanBertels** [louthy/echo-process#47]
This topic was already discussed in last comments in #23.    I created this new issue because the solution there does not work.

Question is: how can I get some information during inboxFn and setupFn telling me that the actor is going to be killed?

Reason: If there are long running operations in setupFn (e.g. slow loading of state) or inboxFn (e.g. slow/big downloads) I want to cancel this if the actor get's killed for whatever reason.

The idea of #23 does not work:

```
var ctx = new CancellationTokenSource();
using (observeUnsafe<Unit>(Self).Subscribe(_ => { }, () => ctx.Cancel())
{
    // use ctx.Token here;
}
```

It does not work because kill is waiting for the inboxFn to finish (implemented as solution for #42, which is a good thing).

One quick hack would be to modify Actor.cs like
```
        public Unit Shutdown(bool maintainState)
        {
            publishSubject.OnCompleted(); // moved above lock

            lock(sync)
            { 
```
but this isn't clean, either, because inboxFn might publish something and this will get lost, then.

I think the best solution would be to add some CancellationToken to ActorContext so one could get it in the same way like one has access to `Self` or `Parent`, now. 

What do you think? Ready for a pull request?

Would be no breaking change because if you don't use the CancellationToken nothing would change. And of course the inboxFn would decide what to do on cancellation (throw or execute successfully in some way).

**Comment by louthy** [comment]
This is very specific to a use-case.  So I don't think carrying a CancellationToken around with every actor is the best use of resource.  I think you could have two actors a parent and a child.  The parent could spawn the child to do the work and pass the CancellationToken to the child.  The parent can then receive the messages for killing and invoke the CancellationToken.

I have now added a `Shutdown` function parameter to the `spawn` functions which will allow you to catch the shutdown and invoke the token if necessary.
