### ISSUE TITLE
Cluster out of synch, reads null metadata when using dispatcher

### ISSUE THREAD

**Issue by OlduwanSteve** [louthy/echo-process#6]
Hi Paul, I've got an exception call stack here and what I think may be a cause.

The exception is occuring during a 'tell' to a dispatcher, and its ultimately coming from Json deserialiser because it's getting a null value:

```
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at 
Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at 
LanguageExt.RedisClusterImpl.<>c__DisplayClass25_0`1.<GetValue>b__0() at 
LanguageExt.RedisClusterImpl.Retry[T](Func`1 f) at 
LanguageExt.ActorDispatchRemote.ValidateMessageType(Object message, ProcessId sender) at 
LanguageExt.ActorDispatchRemote.TellNoIO(Object message, ProcessId sender, String inbox, Type type, TagSpec tag) at 
LanguageExt.ActorDispatchRemote.<>c__DisplayClass13_0.<Tell>b__0() at 
LanguageExt.ProcessOp.IO(Func`1 op) at 
LanguageExt.ActorDispatchRemote.Tell(Object message, ProcessId sender, TagSpec tag) at 
LanguageExt.ActorDispatchGroup.<>c__DisplayClass18_0.<Tell>b__0(IActorDispatch d) at LanguageExt.List.iter[T](IEnumerable`1 list, Action`1 action) at 
LanguageExt.ActorDispatchGroup.Tell(Object message, ProcessId sender, TagSpec tag) at 
LanguageExt.Process.tell[T](ProcessId pid, T message, ProcessId sender) 
```

In ValidateMessageType, it first checks if a process exists and then calls GetValue. It seems like it must be possible for a process to be in the cluster members list, but its metadata does not exist in redis.

Ideally (I think) if this situation occurs the cluster members list would get 'repaired' by removing the dead member.

**Comment by louthy** [comment]
@OlduwanSteve What was the type of the Exception?

**Comment by OlduwanSteve** [comment]
Oops, yep: `System.ArgumentNullException` - message was "Value cannot be null. "

**Comment by louthy** [comment]
Hi Steve, going to close this because I think this is resolved in v2.
