### ISSUE TITLE
Wiki Registered processes Docs Issue

### ISSUE THREAD

**Issue by gregberns** [louthy/echo-process#85]
"roles section" is  a broken link in [Registered processes](https://github.com/louthy/echo-process/wiki/Registered-processes):

```
Things to note are that this isn't an aliveness system (see the roles section for that). A registered Process is registered until:
```

Actual: https://github.com/louthy/lecho-process/wiki/Roles
Expected: https://github.com/louthy/echo-process/wiki/Roles
Error: `lecho-process`

**Comment by louthy** [comment]
Fixed. Thanks!
