### ISSUE TITLE
void vs. Unit return type

### ISSUE THREAD

**Issue by StefanBertels** [louthy/echo-process#9]
This is maybe more related to LanguageExt than Echo.Process but I wonder why you have many Actions (return type void) in your _echo_ code. I'm asking because I'm not sure whether I should replace every `void` by `Unit` in _my_ code.

I know `act`/`fun` will always convert one to each other, so I guess this is more a style question.

So what's the reason for e.g. `Process.logWarn` returning `void` and `Process.publish` returning `Unit`? Do you have a rule of thumb here in echo-process?

**Comment by louthy** [comment]
Probably just some laziness.  Ideally everything `void` would return `Unit` to aid composition.
